class Memoria:
	def __init__(self, cuadrRetorno, arrEntero, arrCuadrado, arrRectangulo, arrCirculo, arrLinea, arrEstrella, arrDecimal, arrBool, arrEnteroTemp, arrCuadradoTemp, arrRectanguloTemp, arrCirculoTemp, arrLineaTemp, arrEstrellaTemp, arrDecimalTemp, arrBoolTemp):
		self.arrEntero = []
		self.arrCuadrado = []
		self.arrRectangulo = []
		self.arrCirculo = []
		self.arrLinea = []
		self.arrEstrella = []
		self.arrDecimal = []
		self.arrBool = []
		self.arrEnteroTemp = []
		self.arrCuadradoTemp = []
		self.arrRectanguloTemp = []
		self.arrCirculoTemp = []
		self.arrLineaTemp = []
		self.arrEstrellaTemp = []
		self.arrDecimalTemp = []
		self.arrBoolTemp = []
		self.cuadrRetorno = 0
		self.listaMem = [arrEntero, arrCuadrado, arrRectangulo, arrCirculo, arrEstrella, arrDecimal, arrBool, arrEnteroTemp, arrCuadradoTemp,arrRectanguloTemp,arrCirculoTemp, arrLineaTemp,arrEstrellaTemp, arrDecimalTemp]
